version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: scheduler-postgres
    restart: always

    environment:
      POSTGRES_DB: scheduler_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: scheduler-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: