spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

scheduler:
  worker:
    count: 4
  poll-interval: 30000
  redis:
    dequeue-timeout: 5