services:

  postgres:
    image: postgres:16

    container_name: scheduler-postgres

    environment:
      POSTGRES_DB: scheduler_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

    container_name: scheduler-redis

    ports:
      - "6379:6379"

  app:
    build: .

    container_name: job-scheduler

    depends_on:
      - postgres
      - redis

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/scheduler_db

      SPRING_DATASOURCE_USERNAME: postgres

      SPRING_DATASOURCE_PASSWORD: postgres

      SPRING_DATA_REDIS_HOST: redis

      SPRING_DATA_REDIS_PORT: 6379

volumes:
  postgres_data: